name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # triggers on push to main branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: docker build -t flask-ci-app .
